# Changes here will be overwritten by Copier
_commit: 2.1.0
_src_path: gh:diamondlightsource/python-copier-template
author_email: gilesknap@gmail.com
author_name: Giles Knap
component_owner: group:default/sscc
description: Python data classes to represent notion API objects
distribution_name: notiondata
docker: false
docs_type: README
git_platform: github.com
github_org: gilesknap
package_name: notiondata
pypi: true
repo_name: notiondata
type_checker: mypy
