apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: notion-data
  title: notion-data
  description: Python data classes to represent notion API objects
spec:
  type: documentation
  lifecycle: experimental
  owner: group:default/sscc